### ISSUE TITLE
Issue running.

### ISSUE THREAD

**Issue by CazadorDev** [SamuelTulach/CanetisRadar#6]
I've never compiled anything before so I tried it out. Was able to get an .exe created using Visual Studio Community, had to set overlay.resx and Mainform.rezx to unblock to successfully compile.

I run the .exe and get the initial dialog window for the program, clicking on Start Overlay throws an unhandled exception error: "Could not load file or assembly 'INIFileParsar Version=2.5.2.0 .........'
Clicking on Continue takes me to a gray box that says 'CanetisRadar Loading...' and nothing happens.

The AppVeyor repo seems to have been removed from inactivity. Hoping you can help a half deaf gamer out!

**Comment by SamuelTulach** [comment]
Pushed change. AppVeyor will build it for you.
